### ISSUE TITLE
Panic in exponential backoff

### ISSUE THREAD

**Issue by vorner** [srijs/rust-tokio-retry#1]
When trying to use the `tokio-retry` with an exponential backoff, I got this panic:

```
thread 'main' panicked at 'attempt to multiply with overflow', /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.0.5/src/strategies/exponential_backoff.rs:27
stack backtrace:
   0:     0x55adfc435fb3 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h0c49f46a3545f908
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55adfc4321a4 - std::sys_common::backtrace::_print::hcef39a9816714c4c
                               at /checkout/src/libstd/sys_common/backtrace.rs:71
   2:     0x55adfc439687 - std::panicking::default_hook::{{closure}}::h7c3c94835e02f846
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x55adfc43920b - std::panicking::default_hook::h0bf7bc3112fb107d
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x55adfc439b5b - std::panicking::rust_panic_with_hook::ha27630c950090fec
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x55adfc439a34 - std::panicking::begin_panic::heb97fa3158b71158
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x55adfc439969 - std::panicking::begin_panic_fmt::h8144403278d84748
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x55adfc4398f7 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x55adfc46444d - core::panicking::panic_fmt::h3b0cca53e68f9654
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x55adfc464384 - core::panicking::panic::h4b991f5abe7d76d5
                               at /checkout/src/libcore/panicking.rs:49
  10:     0x55adfc07a795 - <tokio_retry::strategies::exponential_backoff::ExponentialBackoff as tokio_retry::strategy::RetryStrategy>::delay::ha8fcba7781f4e038
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.0.5/src/strategies/exponential_backoff.rs:27
  11:     0x55adfc062a3b - <tokio_retry::strategy::limited_delay::LimitedDelay<S> as tokio_retry::strategy::RetryStrategy>::delay::h85a101e68b8e7153
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.0.5/src/strategy/limited_delay.rs:19
  12:     0x55adfc061feb - <tokio_retry::strategy::jittered::Jittered<S> as tokio_retry::strategy::RetryStrategy>::delay::h541a52b8cb0cb7d3
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.0.5/src/strategy/jittered.rs:18
  13:     0x55adfc0611b2 - <tokio_retry::future::RetryFuture<S, R, A, F>>::retry::h7f6c44d00636ed8f
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.0.5/src/future.rs:114
  14:     0x55adfc05eb84 - <tokio_retry::future::RetryFuture<S, R, A, F> as futures::future::Future>::poll::h85617c13acb1b65f
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.0.5/src/future.rs:140
  15:     0x55adfc0619c5 - <tokio_retry::future::RetryFuture<S, R, A, F>>::attempt::h624df1b195bdaf8e
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.0.5/src/future.rs:110
  16:     0x55adfc05ecdb - <tokio_retry::future::RetryFuture<S, R, A, F> as futures::future::Future>::poll::h85617c13acb1b65f
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.0.5/src/future.rs:144
  17:     0x55adfc01d5f4 - <futures::future::chain::Chain<A, B, C>>::poll::h8454fca0630cf7d1
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/chain.rs:26
  18:     0x55adfc01880b - <futures::future::and_then::AndThen<A, B, F> as futures::future::Future>::poll::h47c3e4cf7ab9eb7f
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/and_then.rs:32
  19:     0x55adfc022837 - <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll::hadffce42469c94a8
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/map_err.rs:30
  20:     0x55adfc063c50 - <alloc::boxed::Box<F> as futures::future::Future>::poll::hcb56c6b2b4bf35dc
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/mod.rs:106
  21:     0x55adfc01e954 - <futures::future::chain::Chain<A, B, C>>::poll::hdf328769d85559d3
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/chain.rs:26
  22:     0x55adfc02633b - <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::hc78fb7925a0ee080
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/then.rs:32
  23:     0x55adfc021953 - <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::h19adbba2059d6edc
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/loop_fn.rs:93
  24:     0x55adfc063c50 - <alloc::boxed::Box<F> as futures::future::Future>::poll::hcb56c6b2b4bf35dc
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/mod.rs:106
  25:     0x55adfc068b6b - <futures::task_impl::Spawn<F>>::poll_future::{{closure}}::hec8f06d0ce4e9c0b
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:337
  26:     0x55adfc068bbd - <futures::task_impl::Spawn<T>>::enter::{{closure}}::h0149d9c8897c3a25
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:484
  27:     0x55adfc069602 - futures::task_impl::set::{{closure}}::ha611c92aba82b0d8
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:61
  28:     0x55adfc068f83 - <std::thread::local::LocalKey<T>>::with::h16340418cfe8a2a9
                               at /checkout/src/libstd/thread/local.rs:253
  29:     0x55adfc065c1e - futures::task_impl::set::h2e629adaef00391b
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:54
  30:     0x55adfc065463 - <futures::task_impl::Spawn<T>>::enter::h2e3d49fb3e877e29
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:484
  31:     0x55adfc065316 - <futures::task_impl::Spawn<F>>::poll_future::h52e6238f54e295d3
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:337
  32:     0x55adfc065e06 - tokio_core::reactor::Core::run::{{closure}}::h4841042cd993ea91
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:243
  33:     0x55adfc065f90 - <scoped_tls::ScopedKey<T>>::set::h982bddc3d783092f
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  34:     0x55adfc05dbcb - tokio_core::reactor::Core::run::h14de121c50c09099
                               at /home/vorner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:242
  35:     0x55adfbff0f52 - aggregator::reactor::run::h003ce2f24890f7da
                               at /home/vorner/work/pakon/aggregator/src/reactor.rs:112
  36:     0x55adfbfe76f2 - pakon_aggregator::main::hb79cf260b59893f8
                               at /home/vorner/work/pakon/aggregator/src/main.rs:37
  37:     0x55adfc439855 - std::panicking::try::do_call::h689a21caeeef92aa
                               at /checkout/src/libcore/ops.rs:2606
                               at /checkout/src/libstd/panicking.rs:454
  38:     0x55adfc440a1a - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  39:     0x55adfc43a2fa - std::rt::lang_start::hf63d494cb7dd034c
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:57
  40:     0x55adfbfe7b62 - main
  41:     0x7f09505391ff - __libc_start_main
  42:     0x55adfbf7dd29 - _start
  43:                0x0 - <unknown>
```

The retry strategy is created like this and let run for a while. Currently the action always fails:
```rust
    let retry = ExponentialBackoff::from_millis(10)
        .limit_delay(Duration::from_millis(5000))
        .jitter();
```

**Comment by srijs** [comment]
Hi! Thanks for your bug report.

This is indeed something I didn't think much about, and need to fix. In my mind, there are three options we can pursue once the backoff reaches `ULONG_MAX`:

a) Fail with an error
b) Keep the backoff saturated at the maximum value, and keep retrying
c) Stop retrying

I'd be interested to hear your thoughts on the issue.

Also paging @jimmycuadra to get some design input.

**Comment by jimmycuadra** [comment]
I'd say fail with an error. I wish arithmetic in Rust forced you to handle this case instead of risking a panic!

**Comment by vorner** [comment]
I'd prefer b), mostly for two reasons:

* Selfish one, my use case is to try forever if it doesn't work. I want to start fast retries  and settle down after a while, but never too long (basically what the snippet does).
* Failing with error is not what the user asked for or wanted. And, if the user already reached `ULONG_MAX`, then it must have been capped already by a decorator (how many years would the user have to wait without it being capped?). Therefore cupping it at some higher value is not observable.

**Comment by srijs** [comment]
I like that you're pointing out a concrete use-case as the argument for option b, and would agree that terminating the retries in either case (options a and c), hurts the composability of the retry strategy.

Given that the value in question is a 64 bit integer representing the wait time in milliseconds, I also agree that it doesn't seem realistic that the maximum can be reached w/o limiting the delay (as was done in this example), since this would amount to a wait time of several hundred million years.

In theory, that _doesn't_ mean that the value is not observable, for instance if the transformation instead scaled the value in a non-linear way, the flattening out could be observed. I think it is questionable though whether that is of practical concern.

A floating point value would allow us to more closely model applying transformations to an exponentially growing value, all the way into `Infinity`, but I also like using `std::time::Duration` since it properly coveys the meaning of the value and takes care of unit conversion via `from_secs` and `from_millis`.

All in all, I think capping at `std::u64::MAX` will the the least disruptive change that enables your use-case, and I'm happy to go with implementing it.

Please note though that the API has changed since I last released, so as soon as I cut a release with the fix, you will likely need to do some small changes to pick up the new version. I hope that's okay for you.

**Comment by srijs** [comment]
@jimmycuadra thanks for your input, mate! I'll open a separate PR in your repo where we can have a more detailed discussion if we want to handle it differently in `retry`.
